apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountService-deployment
  labels:
    app: accountService
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accountService
  template:
    metadata:
      labels:
        app: accountService

    spec:
      containers:
        - name: accountService
          image: sarose301/accountService:latest
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: accountService-config
                  key: jwt
            #MONGO
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                    name: accountService-config
                    key: dbpath
            #Redis
            - name: Redis_Path
              valueFrom:
                configMapKeyRef:
                    name: accountService-config
                    key: redispath

            - name: Redis_Port
              valueFrom:
                configMapKeyRef:
                    name: accountService-config
                    key: redisport

